### ISSUE TITLE
Scala Native 0.5 Support

### ISSUE THREAD

**Issue by objektwerks** [lolgab/snunit#161]
Do you have any plans to support Scala Native `0.5`? Thanks in advance for your time. Cheers, Objektwerks! :)

**Comment by lolgab** [comment]
I do have! But many dependencies are not released yet, so for now, we can't. I think I will also rewrite it in a Cats Effect first way, when now Cats Effect is, somehow a second-class citizen.

**Comment by objektwerks** [comment]
That's great news! I'm not a Cats Effect user. So if you can also accommodate us simple folk, that would be great! :) Thanks!

**Comment by lolgab** [comment]
SNUnit `0.10.0` was released for Scala Native `0.5`.
Cats Effect support was stopped until they update to Scala Native `0.5` as well.
SNUnit `0.10.1` was just tagged with support for `com-lihaoyi/cask`.
